# Generated by Django 4.0.3 on 2022-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='numero_parte',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
