# Generated by Django 4.0.3 on 2022-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productos_numero_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
