# Generated by Django 4.0.3 on 2022-04-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='status',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='update_add',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='user',
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_favorito',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='itemFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('create_add', models.DateTimeField(auto_now_add=True)),
                ('update_add', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.favoritos')),
            ],
        ),
    ]
