# Generated by Django 4.0.3 on 2022-04-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_productos_favorito_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfavoritos',
            old_name='user',
            new_name='favorit',
        ),
        migrations.RemoveField(
            model_name='itemfavoritos',
            name='create_add',
        ),
        migrations.RemoveField(
            model_name='itemfavoritos',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='itemfavoritos',
            name='status',
        ),
        migrations.RemoveField(
            model_name='itemfavoritos',
            name='update_add',
        ),
    ]
