# Generated by Django 4.0.3 on 2022-04-25 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0007_rename_user_itemfavoritos_favorit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfavoritos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemfavoritos',
            name='favorit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.favoritos'),
        ),
    ]
