# Generated by Django 4.0.3 on 2022-04-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_itemfavoritos_user_alter_itemfavoritos_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
